name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install python packages
      run: |
        pip install requests
    - name: update rates
      env:
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      run: |
        python main.py
        git config --global user.email "hienchu@freelancer.com"
        git config --global user.name "hienchu"
        git add rates_*.json
        git commit -m "rates updated"
        git push
